#!/usr/bin/env bash

generate_snapshot() {
backups_dir="$BACKUPS_DIR"
mkdir -p "$backups_dir"
local output_file="$backups_dir/backup_$(date +%Y%m%d_%H%M%S).json"

echo "--- Generating snapshot: $output_file---"

# Creation of the header according to protocol schema
{
echo "{"
echo '"name": "Snapshot_Auto_'$(date +%Y%m%d)'",'
echo '"description": "Automatic backup generated by Ruvomain-Protocol",'
echo '  "author": "User",'
echo '  "version": "1.0",'
echo '  "apps":['
} > "$output_file"

# Retrieval and formatting of packages
# 'pm list packages -u' displays: package:com.example.app
local packages
packages=$($EXEC pm list packages -u | sed 's/package://g' | grep -v '^$' | sort) || { echo "Error: Failed to retrieve package list.";return 1; }

if [[ -z "$packages" ]]; then
echo "[!] Error : Unable to retrieve the list of packages. Check ADB."
return 1
fi

local pkg_array=($packages)
local total=${#pkg_array[@]}
local count=0

for pkg in "${pkg_array[@]}"; do
count=$((count + 1))

# Writing the app object
echo '    {' >> "$output_file"
echo '      "packageName": "'$pkg'"' >> "$output_file"

# Managing the comma for JSON (no comma for the last element)
if [ "$count" -lt "$total" ]; then
echo '    },' >> "$output_file"
else
echo '    }' >> "$output_file"
fi
done

# Closing the JSON
echo '  ]' >> "$output_file"
echo '}' >> "$output_file"

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
generate_snapshot
fi
