#!/usr/bin/env bash

init_logs-backup() {
mkdir -p "$bl"

find "$bl" -name "ruvomain-backup-*.log" -type f -mtime +30 -delete 2>/dev/null

LOGFILE="$bl"/ruvomain-backup-$(date +%Y%m%d_%H%M%S).log"

exec > >(tee -a "$LOGFILE") 2>&1
}
