#!/usr/bin/env bash

sources() {
# --- Dynamic Path Resolution ---
STYLE_DIR="$REPO_DIR/lib/styles.sh"
ENSURE_DIR="$REPO_DIR/lib/ensure-adb.sh"
ENSUREJQ_DIR="$REPO_DIR/lib/ensure-jq.sh"
LOGS_DIR="$REPO_DIR/lib/logs.sh"
LOGO_DIR="$REPO_DIR/lib/logo.sh"
MODEL_DIR="$REPO_DIR/lib/model.sh"
ENV_DIR="$REPO_DIR/lib/env-detect.sh"
MENU_DIR="$REPO_DIR/lib/menu.sh"
CONFIGS_DIR="$REPO_DIR/Configs"
FINAL_DIR="$REPO_DIR/lib/final.sh"
CHECK_DIR="$REPO_DIR/lib/check_adb.sh"
INSTALLER_DIR="$REPO_DIR/lib/installer.sh"
BACKUP_DIR="$REPO_DIR/lib/backup.sh"
ENVB_DIR="$REPO_DIR/lib/envb.sh"
LOGSBACKUP_DIR="$REPO_DIR/lib/logs-backup.sh"
BACKUPS_DIR="$(dirname "$0")/../ruvomain-backup/backups"

# --- Sources ---
chmod +x "$STYLE_DIR"
chmod +x "$ENSURE_DIR"
chmod +x "$ENSUREJQ_DIR"
chmod +x "$LOGS_DIR"
chmod +x "$LOGO_DIR"
chmod +x "$MODEL_DIR"
chmod +x "$ENV_DIR"
chmod +x "$MENU_DIR"
chmod +x "$FINAL_DIR"
chmod +x "$CHECK_DIR"
chmod +x "$INSTALLER_DIR"
chmod +x "$BACKUP_DIR" 
chmod +x "$ENVB_DIR"
chmod +x "$LOGSBACKUP_DIR"
source "$STYLE_DIR"
source "$ENSURE_DIR"
source "$ENSUREJQ_DIR"
source "$LOGS_DIR"
source "$LOGO_DIR"
source "$MODEL_DIR"
source "$ENV_DIR"
source "$MENU_DIR"
source "$CONFIGS_DIR"
source "$FINAL_DIR"
source "$CHECK_DIR"
source "$INSTALLER_DIR"
source "$BACKUP_DIR" 
source "$ENVB_DIR"
source "$LOGSBACKUP_DIR"
} 
